site_name: TEST PAGE

# Copyright
copyright: Copyright &copy; 2020 Holger Brandl

theme:
  name: material
#  highlightjs: true
#  hljs_languages:
#    - kotlin
#  navigation_depth: 3
#  features:
#    - navigation.expand
#    - navigation.instant
#    - navigation.tabs

markdown_extensions:
#  - codehilite  --> Deprecated
  - pymdownx.highlight:
#      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

#extra_css:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
